#!/usr/bin/env node
// Generates knowledge/index.md from entry frontmatter. Replaces manual maintenance.
// Run after any write operation to keep index current.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENTRIES_DIR = path.join(ROOT, 'knowledge', 'entries');
const INDEX_FILE = path.join(ROOT, 'knowledge', 'index.md');

function extractFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const fm = {};
  for (const line of match[1].split('\n')) {
    const colon = line.indexOf(':');
    if (colon === -1) continue;
    const key = line.slice(0, colon).trim();
    const val = line.slice(colon + 1).trim();
    fm[key] = val;
  }
  return fm;
}

try {
  const files = fs.readdirSync(ENTRIES_DIR).filter(f => f.endsWith('.md')).sort();
  const rows = [];

  for (const file of files) {
    const slug = file.replace('.md', '');
    const content = fs.readFileSync(path.join(ENTRIES_DIR, file), 'utf8');
    const fm = extractFrontmatter(content);
    if (!fm || !fm.title) {
      console.error(`WARN: ${file} missing frontmatter or title`);
      continue;
    }
    const tags = fm.tags ? fm.tags.replace(/[\[\]]/g, '') : '';
    const ns = fm.namespace || '';
    const updated = fm.updated || fm.created || '';
    rows.push(`| ${slug} | ${fm.title} | ${ns} | ${tags} | ${updated} |`);
  }

  const output = [
    '# Knowledge Index',
    '',
    'Generated by generate-index.js — do not edit manually.',
    'Run `node .claude/generate-index.js` after any entry change.',
    '',
    '| slug | title | namespace | tags | updated |',
    '|------|-------|-----------|------|---------|',
    ...rows,
    '',
  ].join('\n');

  fs.writeFileSync(INDEX_FILE, output);
  console.log(`✓ index.md updated — ${rows.length} entries`);
} catch (e) {
  console.error('generate-index failed:', e.message);
  process.exit(1);
}
